apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-rollout
  namespace: clahanstore
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: frontend-ui
        image: vignesh8386/frontend-ui:v1.0.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
  strategy:
    blueGreen: 
      # activeService specifies the service to update with the new template hash at time of promotion.
      activeService: frontend-active-svc
      # previewService specifies the service to update with the new template hash before promotion.
      previewService: frontend-preview-svc
      # autoPromotionEnabled disables automated promotion to allow manual intervention/toggles.
      autoPromotionEnabled: false
